In [33]:
import sqlite3
import pandas as pd
from pathlib import Path
pd.set_option("display.max_colwidth", None) 

DB_PATH = Path("reviews.db")
conn = sqlite3.connect(DB_PATH)
print("✅ Подключено к", DB_PATH)

✅ Подключено к reviews.db

In [34]:
# Таблицы в БД
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)

              name
0          reviews
1       categories
2  sqlite_sequence

In [35]:
# Схема таблицы reviews
pd.read_sql("PRAGMA table_info(reviews)", conn)

   cid            name     type  notnull dflt_value  pk
0    0              id     TEXT        0       None   1
1    1           title     TEXT        0       None   0
2    2            text     TEXT        0       None   0
3    3  published_date     TEXT        0       None   0
4    4          rating  INTEGER        0       None   0
5    5           reply     TEXT        0       None   0
6    6     author_hash     TEXT        0       None   0
7    7      scraped_at     TEXT        0       None   0
8    8      reply_date     TEXT        0       None   0

In [36]:
pd.read_sql("PRAGMA table_info(categories)", conn)

   cid         name     type  notnull dflt_value  pk
0    0           id  INTEGER        0       None   1
1    1   group_type     TEXT        1       None   0
2    2         name     TEXT        1       None   0
3    3  description     TEXT        0       None   0
4    4        count  INTEGER        0       None   0
5    5   review_ids     TEXT        0       None   0
6    6        model     TEXT        0       None   0
7    7  analyzed_at     TEXT        0       None   0

In [41]:
pd.read_sql("SELECT * FROM categories ORDER BY group_type, count DESC", conn)

,id,group_type,name,description,count,review_ids,model,analyzed_at,company
0,1,negative,Скрытые подписки и автопродление,"Пользователи жалуются на неочевидное подключение платных планов (часто при покупке SCHUFA/документов), автоматическое продление и минимальные сроки контрактов, о которых сложно узнать заранее.",20,"[""69d5141c4907e1deb354dd63"", ""698b0e2570516f9d941b55b1"", ""6970f1741faae8e3d32a5935"", ""696a801218b50921d8cc01e0"", ""695d92b0f8bd25f2b880535c"", ""695255a790440df73c218630"", ""6944294ecd5e489268d41f4f"", ""693a15d26f9e70311ae239ed"", ""69280413fb4a66bbbc022aa1"", ""69242b58adb74b85b9d8abca"", ""6921d65cc32ed20655ab8da7"", ""690cb4c7a750f4b105e212d6"", ""68f086c53780e983e7e15ff3"", ""68cc56b70bb46941c67ac8be"", ""68c70f2781a0b3986a037cd1"", ""68b6d7817331b2736fb9d716"", ""68b2ac9ff09a651fde7e0ad0"", ""68ad71f8d980c95bae620f33"", ""68a6dea24f1100e6bae0934a"", ""6882330561b3c8e7fb551cf7""]",gpt-5.2,2026-04-24T15:07:46,NaN
1,5,negative,Нет ответов от арендодателей,"Основная боль — заявки и сообщения остаются без ответа, не назначают просмотры/термины, из-за чего поиск жилья затягивается на месяцы.",16,"[""69b5532ea1271069805b860a"", ""69a7113410dd1234b4dbf1e4"", ""69985bba397e57971842efb8"", ""6998418edf1709b68d4b6b0b"", ""6998372a99060e37a2d341eb"", ""6996704aa294e103a98fbbef"", ""6988c1840adbaf9aacb5a004"", ""696214708deb16ba1198bd85"", ""69600554408757049e6336c7"", ""695d92b0f8bd25f2b880535c"", ""694d0f320d23fc609a20632f"", ""6947c3af9de55338807e8524"", ""69359d46e84d28f9f8b4fe3d"", ""68f64d15eff01f7159e17739"", ""69270528ac343e5a2d9f194a"", ""68a681bf8aabadc78ff1eece""]",gpt-5.2,2026-04-24T15:07:46,NaN
2,2,negative,Ошибочные списания и переплаты,"Сообщают о двойных списаниях, списаниях после отмены, списаниях на неверные суммы/периоды и отсутствии возвратов.",13,"[""69bbbdb02d6b4c65d6e9d8f7"", ""697c6464668fec45c75a62da"", ""696a801218b50921d8cc01e0"", ""6929af01a1f83e19f66b799f"", ""6912d04b406585b8ce075b13"", ""68fe100eb15f8ec1b07bcd0d"", ""68d55fb0620acc48da513141"", ""68aeac7f4edfbbb7cffcdd6e"", ""68cc56b70bb46941c67ac8be"", ""69367b50d7e5bf3a0824e871"", ""6931a2a545c5bed5ccb7ef59"", ""6915a2138cae566e183dfd97"", ""69904e77ffdfb057ccc9e309""]",gpt-5.2,2026-04-24T15:07:46,NaN
3,28,negative,Сложная отмена/продление,"Отмечают, что подписка автоматически продлевается, отмена запутана, а списания продолжаются даже после отмены или при «неактивном» аккаунте.",13,"[""69d40514e8fecbe29a3c7e7f"", ""698c9dc843f415a9918e449e"", ""6929af01a1f83e19f66b799f"", ""6912d04b406585b8ce075b13"", ""68fe100eb15f8ec1b07bcd0d"", ""68cc56b70bb46941c67ac8be"", ""68c70f2781a0b3986a037cd1"", ""68ad71f8d980c95bae620f33"", ""68a6dea24f1100e6bae0934a"", ""69242b58adb74b85b9d8abca"", ""690cb4c7a750f4b105e212d6"", ""695255a790440df73c218630"", ""6882330561b3c8e7fb551cf7""]",gpt-5.2,2026-04-24T15:41:09,immobilienscout24
4,34,negative,Нет ответов арендодателей,Пользователи массово не получают ответов на заявки/сообщения и не могут добиться просмотров (Termin).,12,"[""69b5532ea1271069805b860a"", ""69985bba397e57971842efb8"", ""6998418edf1709b68d4b6b0b"", ""6998372a99060e37a2d341eb"", ""6996704aa294e103a98fbbef"", ""6988c1840adbaf9aacb5a004"", ""696214708deb16ba1198bd85"", ""69600554408757049e6336c7"", ""695d0adb7ca3fba9ecbd6779"", ""694d0f320d23fc609a20632f"", ""68f64d15eff01f7159e17739"", ""69270528ac343e5a2d9f194a""]",gpt-5.2,2026-04-24T15:41:09,immobilienscout24
...,...,...,...,...,...,...,...,...,...
96,97,positive,Качество сервиса,Пользователи отмечают высокий уровень обслуживания и общее положительное впечатление от сервиса.,1,"[""68d50fae368a64e3444c661a""]",gpt-5.2,2026-04-24T15:41:58,immowelt
97,98,positive,Быстрое решение проблем,Обращения в поддержку решаются оперативно и эффективно.,1,"[""669a29de66fc32dce9a677a6""]",gpt-5.2,2026-04-24T15:41:58,immowelt
98,99,positive,Поддержка на английском,Наличие поддержки на английском языке помогает решать вопросы без языковых затруднений.,1,"[""669a29de66fc32dce9a677a6""]",gpt-5.2,2026-04-24T15:41:58,immowelt
99,100,positive,Поиск жилья,Платформа воспринимается как удобное место для поиска и подбора жилья.,1,"[""68d50fae368a64e3444c661a""]",gpt-5.2,2026-04-24T15:41:58,immowelt
100,101,positive,Общее одобрение,"Короткие эмоциональные отзывы без конкретики, выражающие общее довольство.",1,"[""665602dd93fa9ce2845ca67f""]",gpt-5.2,2026-04-24T15:41:58,immowelt

In [23]:
# Общая статистика
pd.read_sql("""
    SELECT
        COUNT(*)                        AS total,
        MIN(published_date)             AS oldest,
        MAX(published_date)             AS newest,
        ROUND(AVG(rating), 2)           AS avg_rating,
        SUM(reply IS NOT NULL)          AS with_reply
    FROM reviews
""", conn)

,total,oldest,newest,avg_rating,with_reply
0,100,2025-07-24T15:20:05.000Z,2026-04-22T16:45:11.000Z,1.67,95

In [24]:
# Распределение по рейтингу
pd.read_sql("""
    SELECT rating, COUNT(*) AS count
    FROM reviews
    GROUP BY rating
    ORDER BY rating DESC
""", conn)

   rating  count
0       5     13
1       4      1
2       3      4
3       2      4
4       1     78

In [38]:
# Все отзывы
df = pd.read_sql("SELECT * FROM reviews ORDER BY published_date DESC", conn)
df

,id,title,text,published_date,rating,reply,author_hash,scraped_at,reply_date
0,69e8def72564b4c9d717d0f6,It's a complete rip-off.,"It's a complete rip-off.\nI only received old apartment listings that had long since expired. Paying for ""Search+"" offers absolutely no benefits. Scammers!",2026-04-22T16:45:11.000Z,1,NaN,a13026554fe4000b,2026-04-24T13:59:36,NaN
1,69e64e19e37a52b5ad30db86,Realtor didn't show,"Realtor didn't show, there were 2 other families and we were all just standing around. He could have emailed or said if he'd be late. No apology email either, plus the property was a mess! Super disappointing.",2026-04-20T18:02:33.000Z,1,"Hello,\n\nThank you for your feedback. We understand how frustrating it is to arrive at a viewing and have the realtor not show up—especially when multiple people are waiting and no communication or follow-up is provided. \nWhile viewings are organized by the respective providers, clear communication and reliability are essential. Please feel free to contact your direct contact person for further feedback.\n\nYour ImmoScout24 Team",b0562b4c3208c404,2026-04-24T15:01:11,2026-04-21T06:18:29.000Z
2,69ddd00d2890bbab1a15a5b9,Excellent!!!!!,Excellent!!!!!,2026-04-14T07:26:37.000Z,5,"Hello Mohan,\n\nmany thanks for your positive review!\n\nYour ImmoScout24 Team",72e0d628c38ac5dc,2026-04-24T15:01:11,2026-04-17T09:02:03.000Z
3,69d5141c4907e1deb354dd63,They sent me to debt collection without a single notification,"I registered on this website through my Apple account with the ""Hide My Mail"" feature that relays the e-mails to my real mail and I have been subscribed to their Plus service with a yearly contract in October 2025 when I moved to Germany. I signed up for this subscription with a credit card which ha",2026-04-07T16:26:36.000Z,1,NaN,135b68c394c652cd,2026-04-24T13:59:36,NaN
4,69d40514e8fecbe29a3c7e7f,Finding a property through this site…,"Finding a property through this site was difficult. The premium option didn’t add much value, and managing the subscription was a bit tricky.",2026-04-06T21:10:12.000Z,1,"Hello, \n\nthank your for your review. We are sorry that you have had struggles, navigating your search. Suchen+ is meant to help you finding a suitable poperty, but can never be a guarantee. If you need any assistance, please feel free to contact our customer service via https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",1f04914aa140e947,2026-04-24T15:01:11,2026-04-09T13:44:55.000Z
...,...,...,...,...,...,...,...,...,...
95,68ad71f8d980c95bae620f33,Good Platform Terrible Service,"ImmoScout functions well as a platform with solid technical infrastructure and reliable performance. However, their business practices raise some concerns that feel inappropriate for a company of their size and market position.\nThe platform operates on a minimum subscription model with automatic ren",2025-08-26T10:36:08.000Z,2,"Hello Parth,\n\nthank you for your constructive feedback about our platform.\n\nWe appreciate that you acknowledge our technical capabilities while raising concerns about our subscription model. When booking, it's indicated that memberships automatically renew for a fee if not cancelled, and we send two confirmation emails upon activation.\n\nIf you'd like to discuss your case further, please contact us at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",c3e3c8e20048e827,2026-04-24T14:49:21,2025-09-12T13:45:47.000Z
96,68a85672fe0e9727039e8f02,"Expensive, paywalled, frustrating — ImmoScout24 disappoints","I get the impression that without Suchen+ (formerly MieterPlus) hardly anything works here. Paying profiles are prioritized in landlords’ inboxes and see exclusive listings before others if you don’t pay, you’re pushed to the back.\n\n“Verification” of credit/identity costs extra (SCHUFA BonitätsCheck",2025-08-22T13:37:22.000Z,1,"Hello Can,\n\nwe appreciate your detailed feedback regarding our Suchen+ service and pricing structure.\n\nWe understand your concerns about the subscription model and market competitiveness. Some landlords prefer applicants with verified documents via Plus memberships, though the housing market remains challenging for everyone.\n\nFeel free to reach out at https://www.immobilienscout24.de/kontakt/ if you'd like to discuss your experience further.\n\nYour ImmoScout24 Team",5a3130f4e9bc06a1,2026-04-24T14:49:21,2025-09-05T13:41:04.000Z
97,68a6dea24f1100e6bae0934a,BE CAREFUL AND CANCEL CONTRACT IMMEDIETLY,"if you rent an apartment you need to buy membership and it s minimum 3 months! That s first red flag and guess what? IF you dont cancel your contract every month they charge money from your account. There is no 0 star, so i give 1 star.",2025-08-21T10:53:54.000Z,1,"Hello Hakan,\n\nwe appreciate you taking the time to share your experience with our membership service.\n\nWe understand your concerns about the subscription model. When booking, it's indicated that the membership automatically renews for a fee if not cancelled. Upon activation, two confirmation emails are sent with all contract details.\n\nShould you need support, please reach out to us at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",82499d9c596dbf51,2026-04-24T14:49:21,2025-09-05T13:36:24.000Z
98,68a681bf8aabadc78ff1eece,1) Misleading people with automated…,1) Misleading people with automated withdrawals. 2) Many of the posts are not real rented apartments. You never hear back.,2025-08-21T04:17:35.000Z,1,"Hello Fuad,\n\nthank you for sharing your concerns about our service.\n\nWe understand your frustration regarding both the subscription process and the lack of responses from landlords. The housing market is very competitive, and many landlords receive numerous applications which they cannot all answer.\n\nIf you need assistance, please contact us at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",c1527f816eaa9693,2026-04-24T14:49:21,2025-09-05T13:35:44.000Z
99,6882330561b3c8e7fb551cf7,Asking for payments for the duration of…,Asking for payments for the duration of inactive account,2025-07-24T15:20:05.000Z,1,"Hello Dinesh,\n\nWe would be happy to look into your case together with you. You can contact us anytime at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",e1efacfe0f4170ec,2026-04-24T14:49:21,2025-08-01T09:37:31.000Z

In [39]:
# Негативные отзывы (рейтинг ≤ 3)
pd.read_sql("""
    SELECT id, rating, title, text, published_date
    FROM reviews
    WHERE rating <= 3
    ORDER BY published_date DESC
""", conn)

,id,rating,title,text,published_date
0,69e8def72564b4c9d717d0f6,1,It's a complete rip-off.,"It's a complete rip-off.\nI only received old apartment listings that had long since expired. Paying for ""Search+"" offers absolutely no benefits. Scammers!",2026-04-22T16:45:11.000Z
1,69e64e19e37a52b5ad30db86,1,Realtor didn't show,"Realtor didn't show, there were 2 other families and we were all just standing around. He could have emailed or said if he'd be late. No apology email either, plus the property was a mess! Super disappointing.",2026-04-20T18:02:33.000Z
2,69d5141c4907e1deb354dd63,1,They sent me to debt collection without a single notification,"I registered on this website through my Apple account with the ""Hide My Mail"" feature that relays the e-mails to my real mail and I have been subscribed to their Plus service with a yearly contract in October 2025 when I moved to Germany. I signed up for this subscription with a credit card which ha",2026-04-07T16:26:36.000Z
3,69d40514e8fecbe29a3c7e7f,1,Finding a property through this site…,"Finding a property through this site was difficult. The premium option didn’t add much value, and managing the subscription was a bit tricky.",2026-04-06T21:10:12.000Z
4,69bbbdb02d6b4c65d6e9d8f7,1,Money problem,"Dear Sir or Madam,\nI hope you are doing well.\nI would like to inform you that an amount was deducted from my account without being refunded. The first deduction was €64.89 in January, and the second was €29.95 in February.\nI have not received a refund for the January amount, and I kindly request you",2026-03-19T11:11:12.000Z
...,...,...,...,...,...
81,68ad71f8d980c95bae620f33,2,Good Platform Terrible Service,"ImmoScout functions well as a platform with solid technical infrastructure and reliable performance. However, their business practices raise some concerns that feel inappropriate for a company of their size and market position.\nThe platform operates on a minimum subscription model with automatic ren",2025-08-26T10:36:08.000Z
82,68a85672fe0e9727039e8f02,1,"Expensive, paywalled, frustrating — ImmoScout24 disappoints","I get the impression that without Suchen+ (formerly MieterPlus) hardly anything works here. Paying profiles are prioritized in landlords’ inboxes and see exclusive listings before others if you don’t pay, you’re pushed to the back.\n\n“Verification” of credit/identity costs extra (SCHUFA BonitätsCheck",2025-08-22T13:37:22.000Z
83,68a6dea24f1100e6bae0934a,1,BE CAREFUL AND CANCEL CONTRACT IMMEDIETLY,"if you rent an apartment you need to buy membership and it s minimum 3 months! That s first red flag and guess what? IF you dont cancel your contract every month they charge money from your account. There is no 0 star, so i give 1 star.",2025-08-21T10:53:54.000Z
84,68a681bf8aabadc78ff1eece,1,1) Misleading people with automated…,1) Misleading people with automated withdrawals. 2) Many of the posts are not real rented apartments. You never hear back.,2025-08-21T04:17:35.000Z
85,6882330561b3c8e7fb551cf7,1,Asking for payments for the duration of…,Asking for payments for the duration of inactive account,2025-07-24T15:20:05.000Z

In [40]:
# Отзывы с ответом компании
pd.read_sql("""
    SELECT id, rating, title, reply, reply_date
    FROM reviews
    WHERE reply IS NOT NULL
    ORDER BY reply_date DESC
""", conn)

,id,rating,title,reply,reply_date
0,69e64e19e37a52b5ad30db86,1,Realtor didn't show,"Hello,\n\nThank you for your feedback. We understand how frustrating it is to arrive at a viewing and have the realtor not show up—especially when multiple people are waiting and no communication or follow-up is provided. \nWhile viewings are organized by the respective providers, clear communication and reliability are essential. Please feel free to contact your direct contact person for further feedback.\n\nYour ImmoScout24 Team",2026-04-21T06:18:29.000Z
1,69ddd00d2890bbab1a15a5b9,5,Excellent!!!!!,"Hello Mohan,\n\nmany thanks for your positive review!\n\nYour ImmoScout24 Team",2026-04-17T09:02:03.000Z
2,69d40514e8fecbe29a3c7e7f,1,Finding a property through this site…,"Hello, \n\nthank your for your review. We are sorry that you have had struggles, navigating your search. Suchen+ is meant to help you finding a suitable poperty, but can never be a guarantee. If you need any assistance, please feel free to contact our customer service via https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",2026-04-09T13:44:55.000Z
3,69bbbdb02d6b4c65d6e9d8f7,1,Money problem,"Hello Bhavik, \n\nThank your for sharing your concerns. We would be happy to review your request in detail and investigate your issue. Please feel free to contact our customer service team directly via happy@scout24.de\n\nYour ImmoScout24 Team",2026-03-19T11:25:47.000Z
4,69b160b9bd43487dd6a17b1f,1,useless and most of the apartments on…,"Hello,\n\nthank you for sharing your feedback. If many listings in your search appear as exchange apartments, that can understandably make the search feel less useful. The types of listings shown depend on the filters and offers provided by individual advertisers. Adjusting search settings can often help tailor the results more closely to what you are looking for. If you would like support with this, please reach out via https://www.immobilienscout24.de/kontakt/.\n\nYour ImmoScout24 Team",2026-03-16T09:29:24.000Z
...,...,...,...,...,...
90,68aeac7f4edfbbb7cffcdd6e,1,"They made me pay schufa twice, lawyers involved","Hello Griseld,\n\nthank you for your feedback regarding your SCHUFA.\n\nWe're sorry you had this experience with our service.\n\nPlease contact us at https://www.immobilienscout24.de/kontakt/ so we can look into your case together.\n\nYour ImmoScout24 Team",2025-09-05T13:56:40.000Z
91,68a85672fe0e9727039e8f02,1,"Expensive, paywalled, frustrating — ImmoScout24 disappoints","Hello Can,\n\nwe appreciate your detailed feedback regarding our Suchen+ service and pricing structure.\n\nWe understand your concerns about the subscription model and market competitiveness. Some landlords prefer applicants with verified documents via Plus memberships, though the housing market remains challenging for everyone.\n\nFeel free to reach out at https://www.immobilienscout24.de/kontakt/ if you'd like to discuss your experience further.\n\nYour ImmoScout24 Team",2025-09-05T13:41:04.000Z
92,68a6dea24f1100e6bae0934a,1,BE CAREFUL AND CANCEL CONTRACT IMMEDIETLY,"Hello Hakan,\n\nwe appreciate you taking the time to share your experience with our membership service.\n\nWe understand your concerns about the subscription model. When booking, it's indicated that the membership automatically renews for a fee if not cancelled. Upon activation, two confirmation emails are sent with all contract details.\n\nShould you need support, please reach out to us at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",2025-09-05T13:36:24.000Z
93,68a681bf8aabadc78ff1eece,1,1) Misleading people with automated…,"Hello Fuad,\n\nthank you for sharing your concerns about our service.\n\nWe understand your frustration regarding both the subscription process and the lack of responses from landlords. The housing market is very competitive, and many landlords receive numerous applications which they cannot all answer.\n\nIf you need assistance, please contact us at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",2025-09-05T13:35:44.000Z
94,6882330561b3c8e7fb551cf7,1,Asking for payments for the duration of…,"Hello Dinesh,\n\nWe would be happy to look into your case together with you. You can contact us anytime at https://www.immobilienscout24.de/kontakt/\n\nYour ImmoScout24 Team",2025-08-01T09:37:31.000Z

In [10]:
# Закрыть соединение когда закончил
conn.close()
print("🔒 Соединение закрыто")

🔒 Соединение закрыто